apiVersion: v1
kind: Service
metadata:
    name: "aksriv03aks-5015"
    labels:
        app: "aksriv03aks-5015"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "aksriv03aks-5015"