on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: aksriv03arc.azurecr.io
        username: ${{ secrets.acr_aksriv03arc_username }}
        password: ${{ secrets.acr_aksriv03arc_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/Files" -f  "Files/DockerFile" -t aksriv03arc.azurecr.io/aksriv03aks:${{ github.sha }}
        docker push aksriv03arc.azurecr.io/aksriv03aks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksriv03aks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aksriv03aksfc2c | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aksriv03aksfc2c`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aksriv03aksfc2c
        container-registry-url: aksriv03arc.azurecr.io
        container-registry-username: ${{ secrets.acr_aksriv03arc_username }}
        container-registry-password: ${{ secrets.acr_aksriv03arc_password }}
        secret-name: aksriv03aksdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: aksriv03aksfc2c
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          aksriv03arc.azurecr.io/aksriv03aks:${{ github.sha }}
        imagepullsecrets: |
          aksriv03aksdockerauth